name: Windows Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: yarn

    - name: Compile source
      run: yarn build:app:unpacked

    - name: Build installer
      working-directory: assets
      run: iscc setup-script.iss /Dversion=1.0.0
          
    - name: Upload portable version
      uses: actions/upload-artifact@v2
      with:
        name: GlucoseTicker
        path: dist/win-unpacked
