name: Windows Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    
    - name: Install dependencies
      run: yarn

    - name: Read package JSON
      id: packagejson
      uses: gregoranders/nodejs-project-info@v0.0.20

    - name: Compile source
      run: yarn build:app:unpacked

    - name: Compile helper
      run: yarn build:helper

    - name: Build installer
      working-directory: assets
      run: iscc setup-script.iss /Dversion=${{ steps.packagejson.outputs.version }}
          
    - name: Upload portable version
      uses: actions/upload-artifact@v2
      with:
        name: GlucoseTicker-${{ steps.packagejson.outputs.version }}-portable
        path: dist/win-unpacked

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: GlucoseTicker-${{ steps.packagejson.outputs.version }}-setup
        path: dist/GlucoseTicker-${{ steps.packagejson.outputs.version }}-setup.exe
